export const MOCK_ERROR_MESSAGE = 'MOCK ERROR MESSAGE'

export const MOCK_CHANGED_ERROR_MESSAGE = 'MOCK CHANGED ERROR MESSAGE'

export const MOCK_ERROR_SUMMARY = [
  MOCK_ERROR_MESSAGE
]

export const MOCK_CHANGED_ERROR_SUMMARY = [
  MOCK_CHANGED_ERROR_MESSAGE
]
